on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    
name: Build TinyTeX Bundles

jobs:
  build:
    runs-on: windows-latest
    name: Build TinyTeX-*.zip

    env:
      CTAN_REPO: https://ctan.math.illinois.edu/systems/texlive/tlnet
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1.1' 
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      # do we want to install CRAN tinytex or dev tinytex ?
      - name: Install tinytex package and its deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Update all packages
        run: |
          try(update.packages(ask = FALSE, checkBuilt = TRUE))
        shell: Rscript {0}

      - name: Add TinyTex to PATH
        run: |
          echo "$APPDATA\TinyTeX\bin\win32" >> $GITHUB_PATH
        shell: bash

      - name: Build TinyTeX-0.zip
        run: |
          Rscript "tools/install-windows-base.R" # the infraonly scheme
          Compress-Archive $Env:APPDATA\\TinyTeX TinyTeX-0.zip

      - name: Build TinyTeX-1.zip
        run: |
          Rscript "tools/install-windows-more.R"  # extra packages for compiling R Markdown
          Compress-Archive $Env:APPDATA\\TinyTeX TinyTeX-1.zip

      - name: Build TinyTeX.zip
        run: |
          Rscript "tools/test-basic.R"  # even more LaTeX packages
          Compress-Archive $Env:APPDATA\\TinyTeX TinyTeX.zip

      - name: Test Installation
        env:
          TINYTEX_INSTALLER: TinyTeX-0
        run: tools\\install-bin-windows.bat
        shell: cmd

      - name: Build tinitex
        run: Rscript tools/build-tinitex.R

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: TinyTex-bundles
          path: |
            TinyTeX*.zip
            tinitex.zip